### PR TITLE
Elasticsearch logging

### PR DESCRIPTION
**Pull request by egourlao**
This PR adds the possibility to send the logs to an Elasticsearch cluster. It can be enabled with the `--elasticsearch.enable` flag, and by pointing to an endpoint with `--elasticsearch.address=<HTTP address>`:

screen shot 2017-07-10 at 10 30 35

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
Why using a forked `go-elastic`?

**Comment by egourlao** [comment]
I'm waiting for tj/go-elastic#3, which adds support for user/password-authentication for Elasticsearch clusters. I'm hoping it gets merged soon.

**Review by johanstokking — DISMISSED** [review]
OK. Code looks good but I wonder if we need to write directly to Elasticsearch from the packet forwarder? How do we secure this? Give everyone a username and password?

**Comment by egourlao** [comment]
What I can imagine is using this only for personal usage, e.g. if a gateway owner wants to follow the logs of their own gateway without going through syslog or dumping the logs in a file. It's not expensive in terms of maintenance (as long as we keep `apex/log`) - if we change our logging system at some point, I can imagine we'll have better insights from the NOC at that point, so that we can afford to drop ES support.

**Review by johanstokking — DISMISSED** [review]
LGTM

**Comment by htdvisser** [comment]
@dotpy3 do we still want this?

**Comment by egourlao** [comment]
I don't think it costs us anything to merge it, given that we've made it clear that the development was put on hold. It can always be useful for specific setups where the Semtech PF behaves improperly (e.g. cellular connectivity), for users that want logs sent to their personal usage.

**Comment by htdvisser** [comment]
Ok, please make sure CI passes first, then we'll merge.

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
