### PR TITLE
Added Raspberry Pi+IMST build&install instructions

### PR DESCRIPTION
**Pull request by egourlao**
This PR adds a Raspberry Pi+IMST build pipeline for GitLab CI, as well as documentation for this build procedure and a basic systemd setup for permanent installation.

### CODE REVIEW

**Comment by johanstokking** [comment]
@jpmeijers please test

**Comment by jpmeijers** [comment]
I have an issue at first run:
```bash
$ ./binary configure
Error when reading config file: Config File ".pktfwd" Not Found in "[/home/pi]"
```

Likely related to https://github.com/TheThingsNetwork/packet_forwarder/pull/16

But after `touch .pktfwd` I get:
```bash
$ ls -la /home/pi
...
-rw-r--r-- 1 pi pi 0 May 10 14:55  .pktfwd
...
$ ./binary configure
Error when reading config file: Config File ".pktfwd" Not Found in "[/home/pi]"
```

But it works when I do:
```bash
$ ./binary --config /home/pi/.pktfwd configure
  INFO If you haven't registered your gateway yet, you can register it either with the console, or with `ttnctl`.
Is this gateway going to be used on the community network?: y
Enter the ID of the gateway: jpm-test
Enter the access key of the gateway: *****************************************************************************************************
  INFO New configuration file saved             ConfigFilePath=/home/pi/.pktfwd.yml
```
But now the config is saved in `.pktfwd.yml`, not in the config I specified.

At least the packet forwarder is running now, but I get an error.
```bash
$ ./packet-forwarder-linux-arm-imst_rpi-native start
  INFO Packet Forwarder for LoRa Gateway        HALVersionInfo=Version: 4.0.0; Options: native;
  INFO Found gateway parameters, getting frequency plans AuthServer=https://account.thethingsnetwork.org GatewayID=jpm-test URL=https://account.thethingsnetwork.org/api/v2/frequency-plans/EU_863_870
  INFO Connecting to TTN discovery server       Address=discover.thethingsnetwork.org:1900
  INFO Connected to discovery server - getting router address
  INFO Connecting to router...                 
  INFO SX1301 board configured                  ClockSource=1 LorawanPublic=true
  INFO Downlinks queuing routine started       
  INFO Configured TX Lut                        Indexes=16
  INFO Radio configured                         EnabledTX=true Frequency=867500000 RSSIOffset=-166 Radio=0 Type=SX1257
  INFO Radio configured                         EnabledTX=false Frequency=868500000 RSSIOffset=-166 Radio=1 Type=SX1257
  INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=0 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=1 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=2 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=3 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=4 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=5 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=200000 Lora multi-SF channel=6 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=400000 Lora multi-SF channel=7 RFChain=0
  INFO LoRa standard channel configured        
  INFO FSK channel configured                  
  WARN No GPS configured, ignoring             
  INFO Starting concentrator...                 DateTime=2017-05-10 15:24:41.002977957 +0000 UTC
 ERROR The program ended following a failure    error=Failed to start concentrator
$ 
```

This means the concentrator is in an undefined state, and should be reset by pulling pin 13 of the concentrator high for 100ns. From the IMST iC880A datasheet, table 6-1:
> Sx1301 Reset,
> for a stable start-up Reset should be at
> high-level for 100 ns (min), once the supply
> voltage is stable . Internally pulled-down with
> 100 kΩ.

I did the reset by hand using a small wire. Now it works:
```
$ ./packet-forwarder-linux-arm-imst_rpi-native start
  INFO Packet Forwarder for LoRa Gateway        HALVersionInfo=Version: 4.0.0; Options: native;
  INFO Found gateway parameters, getting frequency plans AuthServer=https://account.thethingsnetwork.org GatewayID=jpm-test URL=https://account.thethingsnetwork.org/api/v2/frequency-plans/EU_863_870
  INFO Connecting to TTN discovery server       Address=discover.thethingsnetwork.org:1900
  INFO Connected to discovery server - getting router address
  INFO Connecting to router...                 
  INFO SX1301 board configured                  ClockSource=1 LorawanPublic=true
  INFO Downlinks queuing routine started       
  INFO Configured TX Lut                        Indexes=16
  INFO Radio configured                         EnabledTX=true Frequency=867500000 RSSIOffset=-166 Radio=0 Type=SX1257
  INFO Radio configured                         EnabledTX=false Frequency=868500000 RSSIOffset=-166 Radio=1 Type=SX1257
  INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=0 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=1 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=2 RFChain=1
  INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=3 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=4 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=5 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=200000 Lora multi-SF channel=6 RFChain=0
  INFO LoRa multi-SF channel configured         Freq=400000 Lora multi-SF channel=7 RFChain=0
  INFO LoRa standard channel configured        
  INFO FSK channel configured                  
  WARN No GPS configured, ignoring             
  INFO Starting concentrator...                 DateTime=2017-05-10 15:32:09.629398639 +0000 UTC
  INFO Concentrator started, packets can now be received and sent DateTime=2017-05-10 15:32:12.584660475 +0000 UTC
  INFO Waiting for uplink packets              
  INFO Waiting for downlink messages           
  INFO Received uplink packets                  NbPackets=1
  INFO Determined concentrator boot time        BootTime=2017-05-10 15:32:10.155723419 +0000 UTC
  INFO Received valid packets - sending them to the back-end NbValidPackets=1
  INFO Uplink message transmission successful.  CodingRate=4/5 DataRate=SF7BW125 Frequency=867900000 GatewayID=jpm-test Modulation=LORA PayloadSize=23 RSSI=-81 SNR=10.75
```

**Comment by egourlao** [comment]
Regarding the reset feature, do we want to add the feature to the binary, do we want to make a wrapper, or do we want to leave this to the community of RPi users - given that they have already made wrappers for the previous packet forwarder?

**Comment by johanstokking** [comment]
It's a SX1301 feature, but the pin differs per concentrator board. I'd say add it as a configuration setting to the packet forwarder and build it in. Let's not make a mess already with wrappers.

**Comment by egourlao** [comment]
We're going for an additional option (if reasonably possible, limited to Raspberry Pi builds) allowing to set in the configuration a reset pin number, that matches the GPIO pin that needs to be reset at startup.

**Comment by egourlao** [comment]
With the last commit, the `start` command has a new flag, `--reset-pin`, that allows to specify a GPIO pin to which the reset pin of the concentrator is associated with:

```bash
$ ./packet-forwarder-linux-arm-imst_rpi-native start --reset-pin 20
  INFO Packet Forwarder for LoRa Gateway        HALVersionInfo=Version: 4.0.0; Options: native;
  INFO Reset pin specified, resetting concentrator... ResetPin=20
[...]
```

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
