### PR TITLE
antenna_gain prop for poly_pkt_fwd

### PR DESCRIPTION
**Pull request by hb9fxq**
New property/function "antenna_gain" ....eg:  10, /* antenna gain, in dBi */ for gateway_config to reduce RF power to legal boundaries when using higher gain antennas.

### CODE REVIEW

**Comment by hb9fxq** [comment]
no Idea, why travis fails....

**Comment by johanstokking** [comment]
@krippendorf the reason why Travis is failing, is because there's not a Travis file in this repository while it's required to merge. We can omit it.

Can you correct the formatting? See diff here on GitHub; probably spacing vs tab issue

**Comment by hb9fxq** [comment]
THX @johanstokking - Will fix formats in lunch break :-)

**Comment by hb9fxq** [comment]
@johanstokking done.

**Comment by johanstokking** [comment]
Looping in @kersing

These projects have diverged a bit unfortunately; just checking.

**Comment by hb9fxq** [comment]
Good idea, because I think that @kersing 's version https://github.com/kersing/packet_forwarder/blob/cb0f92f1c9a8bd85bf68da0328c2180c9d67dc71/mp_pkt_fwd/src/ttn_transport.c#L243 would drop lots of packages because it only matches rf powers in the txlut table. My version finds the max possible value in txlut table.

**Comment by kersing** [comment]
You might want to consider creating a patch for Lora-net/packet_forwarder. That repo is used by many vendors to create the software for their device. I've the MP source in current testing branch.

**Comment by hb9fxq** [comment]
@kersing OK, I will do that. This branch here is used by the ttn-zh GW used by lot of GWs here. TNX for the feedback. Will port it exactly like done here to Lora-net/packet_forwarder. Can you link the exact target branch to work towards?

@johanstokking this code here runs on my GWs and I can confirm it is working.

**Comment by johanstokking** [comment]
Thanks @krippendorf and @kersing. 

Regarding https://github.com/Lora-net/packet_forwarder; [all pull requests](https://github.com/Lora-net/packet_forwarder/pulls?utf8=%E2%9C%93&q=is%3Apr+) are open or closed, nothing gets merged there. Probably a licensing issue. Anyway, it may be worth reporting there and then hope it gets picked up and applied by the authors.

**Pull request merged**
